version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSGRES_DB: DebitCards
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: